[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-multipart = "0.6.1"
actix-web = "4.5.1"
bcrypt = "0.15.1"                # ← NUEVO: Para passwords
chrono = { version = "0.4.31", features = ["serde"] }
dotenv = "0.15.0"
futures-util = "0.3.28"
jsonwebtoken = "8.3.0"          # Ya lo tienes, perfecto
mongodb = { version = "2.8.0", features = ["bson-chrono-0_4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7.3", features = [ "runtime-tokio-rustls", "postgres", "macros", "chrono", "json", "uuid", "bigdecimal" ] }
bigdecimal = { version = "0.3", features = ["serde"] }
tokio = { version = "1.0", features = ["full"] }        # ← NUEVO: Runtime async
uuid = { version = "1.0", features = ["v4", "serde"] }  # ← NUEVO: IDs únicos
validator = { version = "0.16", features = ["derive"] } # ← NUEVO: Validación
env_logger = "0.10"